### ISSUE TITLE
Add Facebook login

### ISSUE THREAD

**Issue by stagas** [LoveNationArmy/ride#5]
This involves work in both the frontend, the backend and external provider setup.

## Work Items

- [ ] Create app on Facebook
- [ ] Add Facebook login dialog on the frontend
- [ ] Add necessary wiring in the backend to retrieve user data and authorize user
- [ ] Setup automated testing for login/logout
- [ ] Document steps required for users to add FB login to new deployments (and simplify the process as much as possible)
