### ISSUE TITLE
Connect backend with db and setup automated testing

### ISSUE THREAD

**Issue by stagas** [LoveNationArmy/ride#6]
## Work Items

- [ ] Make some demo API endpoints that modify the [state](https://github.com/LoveNationArmy/ride-state/pull/1)
- [ ] Setup automated tests and a **test** db with fixture data to be testing against
- [ ] Setup **dev** db for development (with ability for resets to a state with all cases used in development)
- [ ] Setup **prod** db for production (with ability for migrations when schema changes)

## Important Notes

As we are currently using a **plain json** object as our db, a layer of abstraction **agnostic to the db** needs to be implemented which will allow us to swap to something else in the future without altering any of our business logic or test code.
