### ISSUE TITLE
Setup React state management

### ISSUE THREAD

**Issue by stagas** [LoveNationArmy/ride#7]
## Work Items

- [ ] Research for current React state management solutions
- [ ] Add state managment to the frontend (React) project
- [ ] Setup automated testing for all state changes
