### ISSUE TITLE
CI setup, deploy automation, test coverage, code quality, merge shields

### ISSUE THREAD

**Issue by stagas** [LoveNationArmy/ride#8]
## Work Items

- [x] Research and setup a CI provider (OSS plan)
- [ ] Automate the deployments to **now** when things merge onto **master** and when branches are pushed
- [ ] Setup domain alias for **master** (prod) and provide different environments for branch deploys and test runners
- [ ] Add test coverage tooling to have the ability to examine coverage from GitHub
- [x] Add code quality (eslint, style, cyclomatic complexity) tooling to keep the standard high
- [ ] Add merge shields for when checks are not adequate (missing coverage, too much complexity, eslint errors, etc.)

**Comment by fmmrtns** [comment]
I've chosen Semaphore CI, it's fast, easy to setup, and has an OSS plan. I've created a rule in the master branch, that PR's are merged only when there is 1 review approval and the build passes in the CI. Now we just need to setup the `yarn api:test` and `yarn web:test` commands for the builds to pass.

**Comment by sgimeno** [comment]
I added some real tests for the API (still wip for #6) and Semaphore is arguing about the engines in `package.json`. Any clue?

https://semaphoreci.com/lovenationarmy/ride/branches/feat-6-setup-persistance/builds/1

**Comment by stagas** [comment]
@sgimeno I fixed the engines in this PR (matched them to semaphore's) https://github.com/LoveNationArmy/ride/pull/14 against your branch and it proceeds.

**Comment by fmmrtns** [comment]
Yes the problem is that Semaphore CI only supports node up to 10.10, so the engines setting was preventing the CI to pass:

```sh
[1/5] Validating package.json...

                                                                               
error @: The engine "node" is incompatible with this module. Expected version "10.11".

                                                                               
error @: The engine "yarn" is incompatible with this module. Expected version ">=1.10.0".
```

**Comment by stagas** [comment]
@fmmrtns Can we also introduce something to report cyclomatic complexity? I find it a valuable metric as when there is a lot of branching the code becomes harder to read and maintain and is generally more error-prone. This looks like a good start: https://ariya.io/2013/05/continuous-monitoring-of-javascript-code-complexity but I think there are GitHub hooks nowadays that perform the same thing. Can we do some research there?

**Comment by fmmrtns** [comment]
I didn't even know that existed, I'll take a look 👍
