### ISSUE TITLE
Sync frontend state with backend API calls

### ISSUE THREAD

**Issue by stagas** [LoveNationArmy/ride#9]
Depends on #6.

## Work Items

- [ ] Load initial state from the backend
- [ ] Sync changes that occur in the frontend to the backend
- [ ] Setup automated testing for every state change
